# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main


pool: local

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
    addToPath: true

- script: |
    git config --global user.name 'Ashish dondapati'
    git config --global user.email 'donda297@colostate.edu'
    git clone $(https://github.com/ashish2497/repo)
    cd repo
    # Make your changes here
    git add .
    git commit -m "Automated commit from Azure Pipeline"
    git push origin main
  displayName: 'Commit changes to GitHub'