# Docker
# Build and push an image to Azure Container Registry
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

variables:
  # Container registry service connection established during pipeline creation
  dockerRegistryServiceConnection: '067f4c73-01a4-4dc0-bec6-e8645da342c2'
  imageRepository: 'image1'
  
  containerRegistry: 'registryash.azurecr.io'
  dockerfilePath: '$(Build.SourcesDirectory)/Dockerfile'
  
  tag: '$(Build.BuildId)' 

  # Agent VM image name
  vmImageName: 'ubuntu-latest'

  
    


stages:
- stage: Build
  displayName: Build and push stage
  jobs:
  - job: Build
    displayName: Build
    pool:
      name : 'local'
    steps:
    - powershell: |
        if (-not (Get-Command python3 -ErrorAction SilentlyContinue)) {
          Write-Host "Python 3 could not be found, installing..."
          Invoke-WebRequest -Uri https://www.python.org/ftp/python/3.9.1/python-3.9.1-amd64.exe -OutFile python-installer.exe
          Start-Process -FilePath python-installer.exe -ArgumentList '/quiet InstallAllUsers=1 PrependPath=1' -Wait
        } else {
          Write-Host "Python 3 is already installed"
        }
      displayName: 'Ensure Python 3 is installed'
    - powershell: |
        if (-not (Get-Command az -ErrorAction SilentlyContinue)) {
          Write-Host "Azure CLI could not be found, installing..."
          Invoke-WebRequest -Uri https://aka.ms/installazurecliwindows -OutFile installAzureCLI.msi
          Start-Process msiexec.exe -ArgumentList '/I installAzureCLI.msi /quiet' -Wait
        } else {
          Write-Host "Azure CLI is already installed"
        }
      displayName: 'Install Azure CLI if not already installed'
    
    - task: AzureKeyVault@2
      inputs:
        azureSubscription: 'Azure subscription 1(0c3061a0-6c31-4710-9a05-1f1925e07805)'
        KeyVaultName: 'hubbbbbbbb6732134677'
        SecretsFilter: 'pass'
        RunAsPreJob: true
    - task: AzureCLI@2
      inputs:
       azureSubscription: 'Azure subscription 1(0c3061a0-6c31-4710-9a05-1f1925e07805)'
       scriptType: 'bash'
       scriptLocation: 'inlineScript'
       inlineScript: 'az acr login --name=$(containerRegistry)'

    - task: Docker@2
      displayName: Build and push an image to container registry
      inputs:
        command: buildAndPush
        repository: $(imageRepository)
        dockerfile: $(dockerfilePath)
        containerRegistry: $(dockerRegistryServiceConnection)
        tags: |
          $(tag)
    - task: AzureCLI@2
      inputs:
        azureSubscription: 'Azure subscription 1(0c3061a0-6c31-4710-9a05-1f1925e07805)'
        scriptType: 'bash'
        scriptLocation: 'inlineScript'
        inlineScript: |
          az container create \
          --name day10app \
          --resource-group ooo \
          --image $(containerRegistry)/$(imageRepository):$(tag) \
          --registry-login-server $(containerRegistry) \
          --registry-username registryash  \
          --registry-password $(pass) \
          --dns-name-label aci-demo-ashishdemo
